spring:
  datasource:
    url: jdbc:mysql://192.168.1.122:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    mongodb:
      host: 192.168.1.122
      port: 27017
      database: mall-port
  redis:
    host: 192.168.1.122 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
  rabbitmq:
    host: 192.168.1.122
    port: 5672
    virtual-host: /
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug